db:
  build: ./db
  command: /bin/bash -c "/usr/sbin/sshd; /etc/service/postgres/postgresini.sh; tail -F /etc/passwd"
  ports:
#    - "${PORTPSQL}:5432"
    - "${PORTSSHPSQL}:22"
  expose:
    - "5432"
  volumes:
    - ./db:/code

web:
### The path of docker-compose.yml is the current path
  build: ./web
  command: /bin/bash -c "/usr/sbin/sshd; /etc/service/django/djangoini.sh; python /etc/service/django/manage.py runserver 0.0.0.0:8887; tail -F /etc/passwd"
  links:
    - db
    - nosql
  ports:
#    - "${PORTDjango}:8887"
    - "${PORTSSHDjango}:22"
  expose:
    - "8887"
  volumes:
    - ./web:/code

web2:
  build: ./web2
  command: /bin/bash -c "/usr/sbin/sshd; service apache2 restart; tail -F /etc/passwd"
  links:
    - db
    - nosql
  ports:
    - "${PORTSSHApache}:22"
  expose:
    - "8888"
  volumes:
    - ./web2:/code

nosql:
  build: ./nosql
  command: /bin/bash -c "/usr/sbin/sshd; /etc/service/redis/redisini.sh; tail -F /etc/passwd"
  ports:
#    - "${PORTRedis}:6379"
    - "${PORTSSHRedis}:22"
  expose:
    - "6379"
  volumes:
    - ./nosql:/code

proxy:
  build: ./proxy
  ports:
    - "${PORTNginx}:8080"
  links:
    - web
    - web2
  volumes:
    - ./proxy:/code